<footer>
            <div class="row" style="background-color: #1C1C1C; padding: 2em; margin-top: 4em;">
                <div class="column" style="padding-left: 4em; color: red;">
                    <h2 class="logo">LOCal Entertainment</h2>
                </div>
                <div class="column" style="padding-left: 6em;">
                    <h5 style="color: red;">Inicio</h5>
              
						<p>Home</p>
                        <p>Informações sobre o Site</p>
                        <p>Downloads</p>
                </div>
                <div class="column" style="padding-left: 6em;">
                    <h5 style="color: red;">Sobre-nós</h5>

                        <p>Informações da Empresa</p>
                        <p>Contato</p>
                        <p>Blog</p>
                   
                </div>
				
                <div class="column" style="padding-left: 6em;">
                    <h5 style="color: red;">Suporte</h5>
                        <p>FAQ</p>
						<p>Telefones</p>
                        <p>Chat</p>
                </div>
				
                <div class="column" style="padding-left: 6em;">
					<h5 style="color: red;">Contato</h5>
                        <p>Twitter</p>
                        <p>Facebook</p>
                        <p>Instagram</p>
               
                </div>
            </div>
      
        <div>
            <p align="center" style="background-color: black; padding: 1em; margin-bottom: 0em;">© 2019 Copyright - LOCal Entertainment</p>
		<div>
    </footer>